require "albacore/ncoverreports/reportbase"
require "albacore/ncoverreports/fullcoveragereport"
require "albacore/ncoverreports/summaryreport"

require "albacore/ncoverreports/codecoveragebase"
require "albacore/ncoverreports/branchcoverage"
require "albacore/ncoverreports/methodcoverage"
require "albacore/ncoverreports/symbolcoverage"
require "albacore/ncoverreports/cyclomaticcomplexity"

require "albacore/ncoverreports/reportfilterbase"
require "albacore/ncoverreports/assemblyfilter"
require "albacore/ncoverreports/classfilter"
require "albacore/ncoverreports/documentfilter"
require "albacore/ncoverreports/methodfilter"
require "albacore/ncoverreports/namespacefilter"
